name: CI

on:
  push:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3.3.0
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.PASSWD_DOCKER_HUB }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: |
            itfrancisconeto/mlops_pratice:v1
            itfrancisconeto/mlops_pratice:latest
            
            
          
    
